### PR TITLE
add ipv6 defrag function

### PR DESCRIPTION
**Pull request by RunxiaWan**
Hi all,
I am sorry to send pull request directly. I have written mail to gopacket@googlegroups.com, but I do not get any reply for a long time. I send this pull request to add ipv6 defragment function to gopacket. Basically, it will work like drag.go in ip4drag except it will gopacket.Packet as input to get both IPv6 layer and IPv6Fragment layer. I wonder if this work is worth to be added into gopacket and which changes(I guess there are many) need to be done to the code

Best,
Runxia Wan

### CODE REVIEW

**Comment by RunxiaWan** [comment]
Hi, thanks for replying. Actually my boss has already signed a CLA on behalf of my company and I think my name should be on the list. Do I need to sign it again?

**Comment by gconnell** [comment]
Hmm, it may be that the email associated with your RunxiaWan github account does not match the account that the CLA was signed for.  Could you either resubmit this request from the CLA'd account, or sign the CLA as the RunxiaWan account?

**Comment by RunxiaWan** [comment]
Hi, I just checked the CLA my boss has signed. The problem is that he includes another mail address of mine. I wonder whether it is possible to modify the CLA. If it is, how? Thanks

**Comment by gconnell** [comment]
Unfortunately, I don't have much familiarity with the CLA process besides
the fact that I need folks to sign it.  Would it be possible to resign the
CLA with your other address?

**Comment by RunxiaWan** [comment]
Hi, sorry to reply you late. I let one of my colleagues whose account is on CLA to the the request. His account is songlinjian@gmail.com. Please close this request. Sorry for the inconvenience

**Pull request closed without merging**
