### PR TITLE
Add LPF filter support to afpacket.

### PR DESCRIPTION
**Pull request by JackOfMostTrades**
Linux sockets support [filtering](https://www.kernel.org/doc/Documentation/networking/filter.txt) in the same way as pcap or PF_RING. As with pcap, a program can be generated with the `tcpdump -dd` command and passed into SetLPFFilter(). This adds support for passing in a compiled LPF program to afpacket.

`afpacket.SetLPFFilter( { 0x28, 0, 0, 0x0000000c }, { 0x15, 0, 1, 0x000086dd }, { 0x6, 0, 0, 0x00040000 }, { 0x6, 0, 0, 0x00000000 })`

### CODE REVIEW

**Comment by gconnell** [comment]
Could you take a quick look at the CLA issues presented by GoogleBot and see if you can remedy them on your end?

**Comment by JackOfMostTrades** [comment]
I did need to submit a new CLA, which I did that a little while ago. Is there something I can do to make GoogleBot refresh its check?

**Comment by lhausermann** [comment]
Dear @JackOfMostTrades , I am having a look to existing PR and found yours. Sorry for the long delay. 
Can you provide a documented test case for your code ?

**Comment by lhausermann** [comment]
I am doing a cleanup in the list of PR. @JackOfMostTrades @joelegasse what's the status here ?

**Comment by joelegasse** [comment]
#300 was merged, so I don't think this PR is necessary anymore. You can now just use `SetBPF` with the same struct values.

**Comment by JackOfMostTrades** [comment]
Yea, agreed. #300 resolves this, so I'll go ahead and close this one.

**Pull request closed without merging**
