### PR TITLE
sflow:Add LACP and VLAN Counter Record Types

### PR DESCRIPTION
**Pull request by SH118415**

### CODE REVIEW

**Comment by SH118415** [comment]
@gconnell could you please have a look at this patch

**Comment by gconnell** [comment]
Apologies, but this appears to conflict with https://github.com/google/gopacket/pull/597, which I just merged.  Sorry for the inconvenience on that :(

**Comment by SH118415** [comment]
> Apologies, but this appears to conflict with #597, which I just merged. Sorry for the inconvenience on that :(

@gconnell i am resolving the conflicts and the test is failing could you please have a look

**Comment by SH118415** [comment]
> Apologies, but this appears to conflict with #597, which I just merged. Sorry for the inconvenience on that :(

@gconnell  I have resolved the conflict please have a look :)

**Comment by SH118415** [comment]
@gconnell thanks for the review !!

**Comment by gconnell** [comment]
Thanks!

**Comment by SH118415** [comment]
@gconnell I notice few more changes that are not added by me after the PR is merged. Could you please have a look

**Pull request merged**
