### PR TITLE
VXLAN layer:  moved parsing into a DecodeFromBytes function and added NextLayerType…

### PR DESCRIPTION
**Pull request by danmia**
Made layer compatible with DecodingLayer by:

- moved packet parsing into DecodeFromBytes function (no parsing changed)
- used DecodeFromBytes in layer decode function
- added CanDecode and NextLayerType functions as well

### CODE REVIEW

**Comment by danmia** [comment]
@googlebot I fixed it.

**Comment by danmia** [comment]
@googlebot I signed it!

**Comment by danmia** [comment]
@googlebot I fixed it.

**Comment by jcrussell** [comment]
@gconnell: I tested this and it worked on some VXLAN-tagged PCAP that I have, can we merge it?

**Comment by gconnell** [comment]
Sorry for the delay on this, merged!

**Comment by danmia** [comment]
great!  Thanks so much!

cheers,
Dan

**Pull request merged**
