### PR TITLE
DNS: cache errors to avoid dynamic memory allocations

### PR DESCRIPTION
**Pull request by achille-roussel**
This PR modifies the DNS code to move all constant errors to global variables to avoid dynamic memory allocations on errors.
This will prevent increasing GC load if a DNS server based on gopacket receives a large amount of malformed DNS requests.

Please take a look and let me know if you'd like to see anything changed!

### CODE REVIEW

**Comment by achille-roussel** [comment]
Up?

**Comment by lhausermann** [comment]
@achille-roussel I suppose we were waiting for you to fix the build here before hitting the merge button ;-)
Thanks for the contribution it helps scalability

**Comment by achille-roussel** [comment]
Thanks for getting back.

I could use a bit of guidance on how to fix the build, it seems like the error is unrelated to the change I made, but maybe I'm just not familiar enough with the codebase.

This is what it shows:
```
# github.com/google/gopacket/pcap
./pcap.go:22:18: fatal error: pcap.h: No such file or directory
 #include <pcap.h>
                  ^
compilation terminated.
The command "./.travis.govet.sh" exited with 2.
```

**Comment by lhausermann** [comment]
Mmm, I've just relaunch the build and it does not help... @gconnell any idea ?

**Comment by achille-roussel** [comment]
@lhausermann I synced with the latest version of master, do you think this is good to go now?

**Comment by gconnell** [comment]
Things look good now, thanks!

**Pull request merged**
