### PR TITLE
Added support to pcapgo to read gzip compressed pcap files. Fixes #213

### LINKED ISSUE #213: Support gzip pcap files in pcapgo/read.go
Wireshark will transparently decompress a gzip pcap file. pcapgo.NewReader should check if the first couple of bytes are 0x1f 0x8b, and if so wrap the io.Reader with a gzip.NewReader.

This will allow pcapgo to open compressed pcap files, and  would be consistent with how wireshark's wiretap library does it https://github.com/wireshark/wireshark/blob/90e1232672446e79e75e5c6877310a49f23ae228/wiretap/file_wrappers.c#L575

Happy to send a pull request.

### PR DESCRIPTION
**Pull request by bramp**

### CODE REVIEW

**Comment by bramp** [comment]
Travis seems to be failing in someone else's code :(

**Comment by lhausermann** [comment]
I am out of office and I'd like to take time to review current PR. Having a first look at this one I would like you to update the comments to explain users that gzipped files are supported.

**Comment by bramp** [comment]
No rush on reviewing, but I will send a comment update shortly.

**Comment by lhausermann** [comment]
Great patch... finally nothing to be said, let's merge it

**Pull request merged**
