### PR TITLE
Add sFlow additional tunnel structures

### PR DESCRIPTION
**Pull request by safchain**
Add structures / records described in :
http://sflow.org/sflow_tunnels.txt

Signed-off-by: Sylvain Afchain <safchain@redhat.com>

### CODE REVIEW

**Comment by lhausermann** [comment]
Dear Sylvain, 
What a great patch ! Thanks.
Can you provide a unit test or two ? That would help to make non regression testing more easy, and provide some real example to your code.
Thanks

**Comment by safchain** [comment]
Hello Laurent,

I added two tests.

Thanks

**Comment by lhausermann** [comment]
Thanks merged. 
What are you building next?  We love pull request ;-)
Laurent

**Comment by safchain** [comment]
Thanks for merging the PR. What next ? don't know right now but for sure I will push other patches. Meanwhile if you could have a look at this one : 
https://github.com/google/gopacket/pull/250

Thanks,
Sylvain

**Pull request merged**
