### PR TITLE
Handle ErrFileClosing in packetsToChannel()

### PR DESCRIPTION
**Pull request by hdm**
In addition to EBADF, some distributions (Ubuntu 16.04 LTS at least) return the error `internal/poll.ErrFileClosing` in this function, causing an infinite loop if not handled. Since this is an internal error, the accepted way to check for it appears to be a string match. This is similar to the fix in PR #602. 

It would be great if the ignored errors were a whitelist versus a blacklist; what errors are supposed to be ignored here?

### CODE REVIEW

**Comment by hdm** [comment]
The last push takes a different approach to this and now bails from the loop if more than 100 errors are encountered in a row. If you prefer a different way to handle this, please let me know!

**Comment by notti** [comment]
This is related to #163
I could not really figure out what the reason was for this mechanism (stuff like EINTR reaching this point?). I think it would be better to recover only in known situations where an immediate retry solves the problem.

**Comment by hdm** [comment]
Would you like this updated to only retry once?

**Comment by notti** [comment]
Well more like fail directly in situations that are clearly unrecoverable (EOF and EBADF sounds like that).
Retry should be ok for situations that might recover.
What I meant was that it would be better to have a list of temporary failures - retry for those - and fail for all others. However, I think it's not possible to come up with such a list.
So:
- EOF, BADF (or is there a case where we get BADF in a temporary situation?) fail now
- others try and fail later
Maybe wait a bit before retrying?

**Comment by hdm** [comment]
Thanks! I'll take another swing at this soon.

**Comment by hdm** [comment]
@notti Could you take a peek at the latest when you get a chance?

**Comment by notti** [comment]
Thanks for implementing the suggested changes.

**Pull request merged**
