### PR TITLE
Skip read() with EOF, and add BPF read filter methods

### PR DESCRIPTION
**Pull request by hb9cwp**
How to proceed with the new functions at the bottom of the pull request, e.g. append them here, or try to get them pulled into src/syscall/bpf_bsd.go (where they probably belong)?

### CODE REVIEW

**Comment by gconnell** [comment]
Hey, great change, and sorry to have missed this when it came in.

A few requests before we push this:

1) could the commented code get cleaned out?
2) let's standardize on capitalizing BPF everywhere (in function call names, in particular)

Ping me when those two are done, and I'm happy to merge this in.

**Comment by gconnell** [comment]
Should this be closed out, or is it still in progress?

**Comment by lhausermann** [comment]
@hb9cwp Rolf, any progress on it or I close it?

**Comment by hb9cwp** [comment]
@lhausermann Unfortunately, I have not had a chance to work on this since two years anymore, thus close it, thanks.

**Pull request closed without merging**
