### PR TITLE
Fix for Issue #191

### PR DESCRIPTION
**Pull request by asinghsfdc**
1) Added support for SFlowTypeExpandedCounterSample => SFlowTypeProcessorCounters

2) Added support for SFlowTypeExpandedFlowSample => ExtendedRouterFlowRecord
    Fixed decodeExtendedRouterFlowRecord to parse NextHop properly

### CODE REVIEW

**Comment by lhausermann** [comment]
Hi @asinghsfdc 

Can you sign the CLA so we can start the pull request review / merge to master ?

Laurent

**Comment by asinghsfdc** [comment]
I signed it! on May 14, 2016 19:22 PDT

**Comment by lhausermann** [comment]
Great. Can you resubmit this without a merge commit with the NTP part?

**Comment by asinghsfdc** [comment]
@lhausermann sorry not very git savvy, what are you asking ?

**Comment by bradleyfalzon** [comment]
@asinghsfdc What appears to have happened, is you've made your changes in 31d3279683b8101f883eedfb77d18212d43c827b on 10th May, and the upstream project has made some further changes. You've then merged those upstream changes into your local branch. Ideally, instead of merging upstream changes into your local branch, you would undo all your changes, pull the upstream changes, and then redo your changes - this way upstream has only the one commit (not two, your change and the 'merge commit'). This technique can be accomplished via rebasing, there's a few tutorials on this, here's one that describes both methods (merge and then discusses rebase): http://blogs.atlassian.com/2013/07/git-upstreams-forks/.

You should still be able to rebase your change by running the following:

```
cp /path/to/your/gopacket /tmp/  # make a backup, just in case, almost never required
cd /path/to/your/gopacket
git show                         # should show the merge commit 996a612396aeafc1965a139c1f95ba1ddbc6fa7a
                                 # this is what we want to remove
git rebase -i HEAD~2             # Interactively rebase, doesn't show merge commit 996...
                                 # so want to keep them all by just exiting your editor
                                 # terminal should then show: "Successfully rebased and updated...."
git show                         # should now show 032d368a10063b1e394e436515f868e2aa60d98c
git log                          # should see your actual change 31d3279683b8101f883eedfb77d18212d43c827b
git push -f                      # push your changes back upstream, because you've rewritten history, you need to force
```

This PR should then be updated automatically, and only show 1 commit.

**Comment by asinghsfdc** [comment]
Junked this PR, created a fresh one #201
@lhausermann please merge that one instead

**Pull request closed without merging**
