### PR TITLE
Added an NTP layer (second pull request to fix email problem).

### PR DESCRIPTION
**Pull request by ross-williams**

### CODE REVIEW

**Comment by ross-williams** [comment]
It looks as if the email problem isn't fixed, so I'm closing this pull request too.

**Comment by bradleyfalzon** [comment]
@ross-williams I think what they wanted you to do was:

```
git rebase -i HEAD~6
```

Leave the first pick as is, change the other `pick`s to `s`

```
pick dc6ea56 Added support for NTP.
s bf120b2 Formatted ntp.go.
s dab49d9 Implemented gconnell's suggestions.
s c41ac83 Implemented more changes suggested by gconnell.
s a441594 Implemented more changes suggested by gconnell.
s aa6abfa Added type NTPFixed16Seconds.
```

Modify your commit message

Modify your author
```
git commit --amend --author="Author Name <email@address.com>"
```

Force push
```
git push -f
```

**Comment by bradleyfalzon** [comment]
Apologies if I've misunderstood the issue.

**Comment by ross-williams** [comment]
Thanks very much Bradley. I tried what you suggested, and it seems to have worked.

**Comment by bradleyfalzon** [comment]
No problems, I think you might be able to reopen your closed PR too though?

**Pull request closed without merging**
