### PR TITLE
refactoring - use ICMPv6 type constants

### PR DESCRIPTION
**Pull request by darxriggs**
This reduces duplicate code by using the constants defined for ICMPv6 types & codes.

### CODE REVIEW

**Comment by randstr** [comment]
How about defining constants for the codes too? I like this but it should be neither or both IMO.

```Diff
+const (
+	//ICMPv6TypeDestinationUnreachable
+	ICMPv6CodeNoRouteToDst           = 0
+	ICMPv6CodeAdminProhibited        = 1
+	ICMPv6CodeBeyondScopeOfSrc       = 2
+	ICMPv6CodeAddressUnreachable     = 3
+	ICMPv6CodePortUnReachable        = 4
+	ICMPv6CodeSrcAddressFailedPolicy = 5
+	ICMPv6CodeRejectRouteToDst       = 6
+
+	//ICMPv6TypeTimeExceeded
+	ICMPv6CodeHopLimitExceeded               = 0
+	ICMPv6CodeFragmentReassemblyTimeExceeded = 1
+
+	//ICMPv6TypeParameterProblem
+	ICMPv6CodeErroneousHeaderField   = 0
+	ICMPv6CodeUnrecognizedNextHeader = 1
+	ICMPv6CodeUnrecognizedIPv6Option = 2
+)
+
```

**Comment by randstr** [comment]
I have the same patch, I'll just submit mine too if you don't mind...

**Comment by darxriggs** [comment]
Sure. Go ahead.

**Comment by darxriggs** [comment]
Ok. I'll do. I just saw the duplicate right now.

**Comment by randstr** [comment]
I opened pull request #132, just because I had implemented the code constants too.

**Comment by randstr** [comment]
@darxriggs, are you OK with closing this? Or else I'll close mine and submit my changes after yours. As you wish, just let me know please.

**Comment by randstr** [comment]
Oop, sorry, I totally missed that you implemented the code constants. Apologies, please ignore.

**Comment by randstr** [comment]
Closed pull request #132.

**Pull request merged**
