### PR TITLE
Update ip4defrag with correct limits from RFC791

### PR DESCRIPTION
**Pull request by gustafj**
This patch updates the limits set on the ip4defrag Layer to follow
the definition in RFC791.
Fragment offset according to the RFC:
    This format allows 2**13 = 8192 fragments of 8 octets each for a
    total of 65,536 octets. Every internet module must be able to
    forward a datagram of 68 octets without further fragmentation.
    This is because an internet header may be up to 60 octets, and the
    minimum fragment is 8 octets.

### CODE REVIEW

**Comment by gustafj** [comment]
I signed it!

**Comment by lhausermann** [comment]
Hey @gustafj thanks for patching our IPv4 Defrag. Always good to have new contributor!

As said in my review, I don't really get why you are removing a unit test. I would appreciate to extend / grow the test list, it would ease the merge.. because we are sure the behavior is still the same based on the unit test

**Comment by gustafj** [comment]
Hi, @lhausermann, thanks for the feedback.

The reason is that I am unable to trigger the scenario that was tested with that specific test without extensive mocking.
The test case fails prior to the tested value `IPv4MaximumFragmentListLen` due to triggering the `securityChecks` of `IPv4MaximumFragmentOffset`.
Reason for this is that the ip4defrag discards duplicated fragments, and thus fragment offset needs to change for each fragment, but even with offsets of 1 it will trigger `IPv4MaximumFragmentOffset` check since that one is less that `IPv4MaximumFragmentListLen` (8183 < 8192).
(And I did not want to remove the length check altogether).

**Comment by gconnell** [comment]
I'll admit I straight up didn't believe you that the RFC actually said it allowed fragments as small as 8 bytes... but yeah it does.  Geez, that's tiny :D

**Pull request merged**
