### PR TITLE
Added code to handle the case where the NAME has length zero.

### PR DESCRIPTION
**Pull request by elchavar**

### CODE REVIEW

**Comment by elchavar** [comment]
I signed it!

**Comment by elchavar** [comment]
How can I retrigger the Travis CI build? The build error seems unrelated to the code changes.

**Comment by notti** [comment]
Working on a fix (see my comment on #622 )

**Comment by notti** [comment]
The current ci error is now due to this pull request (linter complains about return in if block followed by an else block).

**Comment by notti** [comment]
Thanks for the contribution

**Pull request merged**
