### PR TITLE
Adding additional parsing capabilities to layers/igmp.go

### PR DESCRIPTION
**Pull request by slon**
This pull request reopens #160

I fixed comments regardless code style.

### CODE REVIEW

**Comment by slon** [comment]
I signed it!

**Comment by lhausermann** [comment]
Hi @slon 

Is it normal that you removed all the comments explaining the structs and functions?

Laurent

**Comment by slon** [comment]
Sorry, I didn't intend to do that. Could you point me to specific line where comment was removed?

I moved lines inside comments because of this suggestion in previous pull-request https://github.com/google/gopacket/pull/160#discussion_r50157356

**Comment by slon** [comment]
Hi @lhausermann 

Would you please take a look at this PR?

**Comment by lhausermann** [comment]
I have added a note where struct comment here removed.
I'll merge the PR right after your commit. 

Great patch thanks for supporting Gopacket

**Comment by slon** [comment]
@lhausermann ping

**Pull request merged**
