### PR TITLE
Adding OVS-SFlow Counter_Record_Type.

### PR DESCRIPTION
**Pull request by dvandra**
Co-authored-by: Asma Suhani <suhu118415@gmail.com>

### CODE REVIEW

**Comment by dvandra** [comment]
> I signed it!

**Comment by SH118415** [comment]
I have signed it!!

**Comment by SH118415** [comment]
I signed it

**Comment by dvandra** [comment]
I signed it!

**Comment by dvandra** [comment]
I am ok with commits being contributed to this project!

**Comment by SH118415** [comment]
I am ok with commits being contributed to this project!

**Comment by dvandra** [comment]
What should be the next step in-order to set the 'cla' label to 'yes'?

**Comment by gconnell** [comment]
Hey, sorry for the delay (holiday time!) and for the issue with the CLA.

Generally, this problem is caused if someone has their git author set to two slightly different emails on two different machines, or something like that.  If you wouldn't mind, could you do the following for the commits in this request, using your github.com's email address:

https://stackoverflow.com/questions/3042437/how-to-change-the-commit-author-for-one-specific-commit

**Comment by dvandra** [comment]
I signed it!

**Comment by dvandra** [comment]
I signed it!

**Comment by dvandra** [comment]
I signed it!

**Comment by dvandra** [comment]
> Hey, sorry for the delay (holiday time!) and for the issue with the CLA.
> 
> Generally, this problem is caused if someone has their git author set to two slightly different emails on two different machines, or something like that. If you wouldn't mind, could you do the following for the commits in this request, using your github.com's email address:
> 
> https://stackoverflow.com/questions/3042437/how-to-change-the-commit-author-for-one-specific-commit

Hey, Thank you so much!
So, i did this with my primary email, but with Co-Author in single commit (https://github.com/google/gopacket/pull/573#issuecomment-447307329) Is it ok only with this?

**Comment by dvandra** [comment]
@gconnell , For the CLA issue, we have raised new independent Pull Requests and we are going to close this one! 
I hope i will get your reviews soon!

**Pull request closed without merging**
