### PR TITLE
Allow to cancel the PacketSource.Packets() underlying Goroutine

### PR DESCRIPTION
**Pull request by baez90**
see #892 for background and explanations

### CODE REVIEW

**Comment by baez90** [comment]
@googlebot I signed it!

**Comment by sud0nick** [comment]
Any idea when this might get merged?  It would be a great addition.

**Comment by baez90** [comment]
@gconnell any chance to get a review or any other kind of feedback?

**Comment by domdom82** [comment]
this looks like a great PR! I wonder if the project is still alive...?

@gconnell since you have the most commits, I assume you are the maintainer?

**Comment by shiqinfeng1** [comment]
@baez90  why closed？ It's very useful for us！

**Comment by baez90** [comment]
It's merged in [gopacket/gopacket](/gopacket/gopacket) which is a fork of this project that is maintained  :wink:

**Pull request closed without merging**
