### PR TITLE
Implement DecodingLayer interface for SCTP

### PR DESCRIPTION
**Pull request by kor44**
Now can use SCTP layer in NewDecodingLayerParser like TCP, UDP

### CODE REVIEW

**Comment by kor44** [comment]
I signed it!

**Comment by lhausermann** [comment]
Hi. Thanks for your contribution. Looks like you added a test for payload length less than 12. Is it a normal case ? If so, please add a unit test. If not, please trigger an error.

Laurent

**Comment by kor44** [comment]
Hi. Can you clarify line number: 71 or 80?

**Comment by lhausermann** [comment]
To be honest, I didn't spot the line 71... which is great. In fact, line 80 is useless. Please just do the safety check first and next consider you are above 12.

**Comment by kor44** [comment]
You are right. I removed this verificaction

**Pull request merged**
