### PR TITLE
Add Support for Diameter Protocol over TCP

### PR DESCRIPTION
**Pull request by tadamra**

### CODE REVIEW

**Comment by tadamra** [comment]
@googlebot I fixed it

**Comment by tadamra** [comment]
@googlebot I fixed it

**Comment by tadamra** [comment]
@googlebot I fixed it

**Comment by notti** [comment]
See #587 for tcp discussion

**Comment by tadamra** [comment]
I will close this merge request since it is covering Diameter as a layer instead of a stream. Possibly I will add diameter stream support in another merge request if I figure out a possible way to integrate such a thing beautifully in Gopacket.

**Pull request closed without merging**
