### PR TITLE
Add SerializeTo methods to RadioTap and Dot11 types

### PR DESCRIPTION
**Pull request by kanemathers**

### CODE REVIEW

**Comment by kanemathers** [comment]
I signed it

**Comment by kanemathers** [comment]
Any feedback on this?

I'm currently using this branch in my own code and would prefer to be using the official release of gopacket rather than my own fork.

**Comment by gconnell** [comment]
Thanks a ton for the help!

**Comment by kanemathers** [comment]
My pleasure

**Pull request merged**
