### PR TITLE
DNS serialization fixes

### PR DESCRIPTION
**Pull request by jdknezek**
In attempting to port some code to use gopacket, I noticed some errors and gaps in the DNS packet encoding. Here are some fixes for them.

### CODE REVIEW

**Comment by lhausermann** [comment]
Hi.

Would sign the CLA?
Is this duplicated with PR #199?

Laurent

**Comment by jdknezek** [comment]
I'm awaiting approval from my employer on the CLA. It does appear that some of these issues would be fixed by #199, though I also implemented some additional record types.

**Comment by lhausermann** [comment]
Any news @jdknezek ?

**Comment by jdknezek** [comment]
So sorry for the delay... I finally have verbal approval and have submitted the corporate CLA to our authorized signer. I'll comment as soon as it's signed.

**Comment by jdknezek** [comment]
Whew, the CLA has finally been signed. It should be signed as the corporation "AmpThink".

**Comment by lhausermann** [comment]
Just as a double check : is the git commits log included your company name and email ? If I understand correctly(I am not a CLA expert nor a Google employee) that's required.

**Comment by gconnell** [comment]
Quick ping on this.  Is there currently anything stopping this merge?

**Comment by tzneal** [comment]
It's the CLA I think, the following commits have an author of jdknezek@gmail.com:

5a08e8b3283cd0bc00e9e631cfe6168971e35423
214982a0b64d139a2cb2fffa2db0fd614b035527
04fbcd74e029b4f6fd2818fb4eb9257e9b184e28
36a3fefb479cec811a433d90832dee1fbb11b6be
cad097cb76ffcf48ffd16723ed86862581e80e17

While these two have an author of jonathan.knezek@ampthink.com:

da71b7ee7c5e091695e05f865f8230491f553da1
6647fddc095a0ec046eae60b9c9ec0e54d616927

@jdknezek, to fix it in your dns-fixes branch:
```
git rebase -i -p f4807986c9ee46845a35c59a382d6ccd9304b320
# In the editor, replace 'pick' with 'edit' in each of the first five lines

# Then, for each edit commit (total of five times) run:
git commit --amend --author "Jonathan Knezek <jonathan.knezek@ampthink.com>" 
git rebase --continue

# Finally push the rewritten changes with the correct author information
git push -f
```

**Comment by jdknezek** [comment]
Thank you very much for the reminder and walkthrough on the rebase. I've completed it.

**Pull request merged**
